name: Build AutoFlip macOS-arm64

on:
  workflow_dispatch:
  push:
    paths: [".github/workflows/build_autoflip.yml"]

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: brew install bazelisk opencv ffmpeg pkg-config

    - name: Patch only OPENCV paths (no CoreFoundation edits)
      run: |
        sed -i '' 's#/usr/local#/opt/homebrew/Cellar#g' WORKSPACE
        OPENCV_VER=$(ls $(brew --cellar opencv) | sort -V | tail -1)
        OPENCV_BUILD=third_party/opencv_macos.BUILD
        sed -i '' "s#^PREFIX = .*#PREFIX = \"opencv/${OPENCV_VER}\"#" $OPENCV_BUILD
        sed -i '' "s#include/opencv2#include/opencv4/opencv2#g"        $OPENCV_BUILD
        sed -i '' "s#paths.join(PREFIX, \"include/\")#paths.join(PREFIX, \"include/opencv4\")#" $OPENCV_BUILD

    - name: Build AutoFlip
      env: { HERMETIC_PYTHON_VERSION: "3.12" }
      run: |
        bazelisk build -c opt --define MEDIAPIPE_DISABLE_GPU=1 \
          --cpu=darwin_arm64 \
          mediapipe/examples/desktop/autoflip:run_autoflip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: run_autoflip-macos-arm64
        path: bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip
